import type { Metadata } from "next";
import Link from "next/link";
import { FaqList } from "@/src/components/faq-list";
import { PageHero } from "@/src/components/page-hero";
import { homeFaqs } from "@/src/config/content";
import { CABINET_URL, TELEGRAM_BOT_URL } from "@/src/config/links";

export const metadata: Metadata = { title: "Поддержка", description: "Инструкции, кабинет и Telegram-бот ST VILLAGE." };

export default function SupportPage() { return <><PageHero eyebrow="Поддержка" title="Помощь, когда она нужна" text="Используйте готовые инструкции, откройте отдельный личный кабинет или сразу перейдите в официального Telegram-бота." /><section className="section-shell page-content support-layout"><aside className="support-nav glass-card"><h2>Разделы помощи</h2><Link href="/connect">Первое подключение</Link><Link href="/pricing">Тарифы и периоды</Link><Link href="/status">Состояние сервиса</Link><Link href="#faq">Популярные вопросы</Link><a href={CABINET_URL} target="_blank" rel="noreferrer">Личный кабинет ↗</a><a href={TELEGRAM_BOT_URL} target="_blank" rel="noreferrer">Telegram-бот ↗</a></aside><div><div className="article-grid"><article className="article-card"><span className="article-category">Начало работы</span><h2>Мастер подключения</h2><p>Выберите платформу и получите последовательность действий для своего устройства.</p><Link className="text-link" href="/connect">Открыть инструкцию <span>→</span></Link></article><article className="article-card"><span className="article-category">Клиентам</span><h2>Личный кабинет</h2><p>Отдельный клиентский портал связан с ботом и открывается напрямую с сайта.</p><a className="text-link" href={CABINET_URL} target="_blank" rel="noreferrer">Открыть кабинет <span>↗</span></a></article><article className="article-card"><span className="article-category">Telegram</span><h2>Официальный бот</h2><p>Быстрый переход в связанного Telegram-бота ST VILLAGE.</p><a className="text-link" href={TELEGRAM_BOT_URL} target="_blank" rel="noreferrer">Открыть бота <span>↗</span></a></article></div><div id="faq" className="support-faq"><h2>Популярные вопросы</h2><FaqList items={homeFaqs} /></div></div><style>{`.support-faq{padding-top:68px}.support-faq>h2{font-size:30px;letter-spacing:-.04em;margin-bottom:24px}`}</style></section></>; }
