import type { Metadata } from "next";
import Link from "next/link";
import { FaqList } from "@/src/components/faq-list";
import { PageHero } from "@/src/components/page-hero";
import { homeFaqs } from "@/src/config/content";

export const metadata: Metadata = { title: "Поддержка", description: "Инструкции и ответы на вопросы о ST VILLAGE." };

export default function SupportPage() { return <><PageHero eyebrow="Поддержка" title="Помощь, когда она нужна" text="Начните с готовых инструкций или перейдите в кабинет, чтобы создать обращение с защищённой историей сообщений." /><section className="section-shell page-content support-layout"><aside className="support-nav glass-card"><h2>Разделы помощи</h2><Link href="/connect">Первое подключение</Link><Link href="/pricing">Тарифы и периоды</Link><Link href="/status">Состояние сервиса</Link><Link href="#faq">Популярные вопросы</Link></aside><div><div className="article-grid"><article className="article-card"><span className="article-category">Начало работы</span><h2>Мастер подключения</h2><p>Выберите платформу и получите последовательность действий для своего устройства.</p><Link className="text-link" href="/connect">Открыть инструкцию <span>→</span></Link></article><article className="article-card"><span className="article-category">Диагностика</span><h2>Проверка состояния</h2><p>Узнайте, доступны ли фактические данные мониторинга и есть ли технические работы.</p><Link className="text-link" href="/status">Проверить статус <span>→</span></Link></article><article className="article-card"><span className="article-category">Обращения</span><h2>Поддержка в кабинете</h2><p>История обращений и сообщения привязываются к защищённой пользовательской сессии.</p><Link className="text-link" href="/login">Перейти ко входу <span>→</span></Link></article></div><div id="faq" className="support-faq"><h2>Популярные вопросы</h2><FaqList items={homeFaqs} /></div></div><style>{`.support-faq{padding-top:68px}.support-faq>h2{font-size:30px;letter-spacing:-.04em;margin-bottom:24px}`}</style></section></>; }
